"""Convert enum columns to varchar

Revision ID: e8507d3b0332
Revises: add_rag_tables
Create Date: 2025-07-04 12:28:35.128894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8507d3b0332'
down_revision: Union[str, Sequence[str], None] = 'add_rag_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flow_templates_created_at'), table_name='flow_templates')
    op.drop_index(op.f('ix_flow_templates_is_public'), table_name='flow_templates')
    op.alter_column('rag_collections', 'status',
               existing_type=postgresql.ENUM('active', 'learning', 'error', 'inactive', name='ragcollectionstatus'),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::ragcollectionstatus"))
    op.drop_constraint(op.f('uq_rag_collections_qdrant_collection_name'), 'rag_collections', type_='unique')
    op.drop_index(op.f('ix_rag_collections_qdrant_collection_name'), table_name='rag_collections')
    op.create_index(op.f('ix_rag_collections_qdrant_collection_name'), 'rag_collections', ['qdrant_collection_name'], unique=True)
    op.alter_column('rag_documents', 'file_type',
               existing_type=postgresql.ENUM('pdf', 'docx', 'txt', 'md', 'html', name='ragdocumenttype'),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('rag_documents', 'status',
               existing_type=postgresql.ENUM('pending', 'processing', 'completed', 'error', 'deleted', name='ragdocumentstatus'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::ragdocumentstatus"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rag_documents', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'processing', 'completed', 'error', 'deleted', name='ragdocumentstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::ragdocumentstatus"))
    op.alter_column('rag_documents', 'file_type',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('pdf', 'docx', 'txt', 'md', 'html', name='ragdocumenttype'),
               existing_nullable=False)
    op.drop_index(op.f('ix_rag_collections_qdrant_collection_name'), table_name='rag_collections')
    op.create_index(op.f('ix_rag_collections_qdrant_collection_name'), 'rag_collections', ['qdrant_collection_name'], unique=False)
    op.create_unique_constraint(op.f('uq_rag_collections_qdrant_collection_name'), 'rag_collections', ['qdrant_collection_name'])
    op.alter_column('rag_collections', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('active', 'learning', 'error', 'inactive', name='ragcollectionstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::ragcollectionstatus"))
    op.create_index(op.f('ix_flow_templates_is_public'), 'flow_templates', ['is_public'], unique=False)
    op.create_index(op.f('ix_flow_templates_created_at'), 'flow_templates', ['created_at'], unique=False)
    # ### end Alembic commands ###
